# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop", "feat" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: fetch source code
      uses: actions/checkout@v3
    - name: Build test
      run: |
        xcodebuild -project ./instagram-iOS/instagram-iOS.xcodeproj -scheme Instagram-iOS -destination "platform:iOS Simulator, id:004DCB5F-255C-4ECE-9C55-651D4312C607, OS:16.2, name:iPhone 14"
        xcpretty --color --simple
